import './globals.css'
import PreHeader from "@/components/layout/PreHeader/PreHeader";
import Header from "@/components/layout/Header/Header";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <PreHeader/>
      <Header/>
      {children}
      </body>
    </html>
  )
}
